// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1I63uLXuApD29c9aE4kpCWuIGLzMXAZk',
    appId: '1:67457599471:web:f5a0179d586fd75b2ed81a',
    messagingSenderId: '67457599471',
    projectId: 'ecommerceapp-f6724',
    authDomain: 'ecommerceapp-f6724.firebaseapp.com',
    storageBucket: 'ecommerceapp-f6724.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjoXYU0wmYtz12nXe0zqJsz4SEweRGdB4',
    appId: '1:67457599471:android:3d1f60d7db5ef0152ed81a',
    messagingSenderId: '67457599471',
    projectId: 'ecommerceapp-f6724',
    storageBucket: 'ecommerceapp-f6724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHF0-ZPzbGvE-qgQjP3BSpmekh1Dn7M8',
    appId: '1:67457599471:ios:3d70bbca1dce217a2ed81a',
    messagingSenderId: '67457599471',
    projectId: 'ecommerceapp-f6724',
    storageBucket: 'ecommerceapp-f6724.appspot.com',
    androidClientId: '67457599471-hbs800n1mi6j9sr9jl709mjc0r0onl57.apps.googleusercontent.com',
    iosClientId: '67457599471-sq1fet023rt30ag1ru0amct76rt41lkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtHF0-ZPzbGvE-qgQjP3BSpmekh1Dn7M8',
    appId: '1:67457599471:ios:3d70bbca1dce217a2ed81a',
    messagingSenderId: '67457599471',
    projectId: 'ecommerceapp-f6724',
    storageBucket: 'ecommerceapp-f6724.appspot.com',
    androidClientId: '67457599471-hbs800n1mi6j9sr9jl709mjc0r0onl57.apps.googleusercontent.com',
    iosClientId: '67457599471-sq1fet023rt30ag1ru0amct76rt41lkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1I63uLXuApD29c9aE4kpCWuIGLzMXAZk',
    appId: '1:67457599471:web:df7018b559f1d0a82ed81a',
    messagingSenderId: '67457599471',
    projectId: 'ecommerceapp-f6724',
    authDomain: 'ecommerceapp-f6724.firebaseapp.com',
    storageBucket: 'ecommerceapp-f6724.appspot.com',
  );

}